coltrane/urls.py
from django.conf.urls.defaults import *
from coltrane.models import Category, Entry, Link
from django.views.generic import dates
from django.views.generic.list import ListView
# from tagging.models import Tag
# from tagging.views import tagged_object_list
from coltrane.views import EntryList

entry_view_params = {'queryset': Entry.live.all(), 'date_field': "pub_date"}

urlpatterns = patterns('',
    
    # Entry URLs
    
    url(r'^/?$',
            EntryList.as_view(**entry_view_params),
            name='coltrane_entry_archive_index'),
    url(r'^/(?P<year>\d{4})/?$',
            dates.YearArchiveView.as_view(**entry_view_params),
            name='coltrane_entry_archive_year'),
    url(r'^/(?P<year>\d{4})/(?P<month>\w{3})/?$',
            dates.MonthArchiveView.as_view(**entry_view_params),
            name='coltrane_entry_archive_month'),
    url(r'^/(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/?$',
            dates.DayArchiveView.as_view(**entry_view_params),
            name='coltrane_entry_archive_day'),
    url(r'^/(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/?$', 
            dates.DateDetailView.as_view(**entry_view_params),
            name='coltrane_entry_detail'),
    
    url(r'^/(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/?$', 
            dates.DateDetailView.as_view(**entry_view_params),
            name='coltrane_entry_detail'),
    
    # Link URLs
    
    url(r'^/links/?$',
            dates.ArchiveIndexView.as_view(model=Link, date_field="pub_date"),
            name='coltrane_link_archive_index'),
    url(r'^/links/(?P<year>\d{4})/?$',
            dates.YearArchiveView.as_view(model=Link, date_field="pub_date"),
            name='coltrane_link_archive_year'),
    url(r'^/links/(?P<year>\d{4})/(?P<month>\w{3})/?$',
            dates.MonthArchiveView.as_view(model=Link, date_field="pub_date"),
            name='coltrane_link_archive_month'),
    url(r'^/links/(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{1,2})/?$',
            dates.DayArchiveView.as_view(model=Link, date_field="pub_date"),
            name='coltrane_link_archive_day'),
    url(r'^/links/(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/?$', 
            dates.DateDetailView.as_view(model=Link, date_field="pub_date"),
            name='coltrane_link_detail'),
    
    
    
    # Category URLs
    
    url(r'^/categories/$', ListView.as_view(model=Category), 
            name='coltrane_category_list'),
    
    url(r'^/categories/(?P<slug>[-\w]+)/$', 'coltrane.views.category_detail',
            name='coltrane_category_detail'),
    
    # # Tag URLs
    
    # url(r'^/tags/$', ListView.as_view(model=Tag), name='coltrane_tag_list'),
    
    # # url(r'^/tags/entries/(?P<tag>[-\w]+)/$', tagged_object_list(
            # # queryset_or_model=Entry.live.all())(
            # # template_name='coltrane/entries_by_tag.html',
            # # ),
            # # name='entries_by_tag'),
    # # url(r'^/tags/links/(?P<tag>[-\w]+)/$', 'tagging.views.tagged_object_list',
            # # { 'queryset_or_model': Link,
              # # 'template_name': 'coltrane/links_by_tag.html'
            # # }, name='links_by_tag'),
    # url(r'/tags/((?P<tag>[-\w]+)/$)', 'coltrane.views.all_items_by_tag',
            # name='coltrane_all_items_by_tag',) 

     )

osov/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.detail import DetailView
from importanciator.models import ImportantContent
from django.views.generic import TemplateView
from os import path
from coltrane.views import FilteredList


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    url(r'^admin/?', include(admin.site.urls)),
    
    # Geofiltering system
    url(r'^filtered/(?P<section>\w+)/(?P<location>\w+)/?$',
        FilteredList.as_view(), name='content_filtered_by_location'),
    # Blog section
    url(r'^article', include('coltrane.urls')),
    # Photo section
    url(r'^photo', include('photogallery.urls')),
    # Video section
    url(r'^video', include('videogallery.urls')),
    # Contacts section
    url(r'^contacts/', 'mailit.views.contacts_page', name="contacts"),
    # Succesfully sent fast contast stuff
    url(r'^contacts-send-success/', 
        TemplateView.as_view(template_name="osov/contacts_send_success.html"),
        name="contacts_send_success"),
    # Main page
    url(r'^/?', 'importanciator.views.render_main', name='home_page'),
    # Filtratioin by location
    url(r'^thank_you_for_application/?', 
        TemplateView.as_view(template_name="osov/thank_you.html"), name='thank_you'),
    # Django comments
    url(r'^comments/', include('django.contrib.comments.urls')),
    
    
    (r'^tinymce/', include('tinymce.urls')),
   
)

coltrane/models.py

import datetime
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from markdown2 import markdown
from os.path import join, splitext, split
from os import listdir
from osov.settings import SLIDER_THUMBNAIL_SIZE, STANDARD_THUMBNAIL_SIZE, IMG_UPLD_DIR, MEDIA_URL
from tagging.models import Tag
from tagging.fields import TagField
from tinymce import models as tinymce_models
from coltrane.aux_utils import transliterate, get_image_path, \
                               produce_resized_image, space_to_underscore


#---------- Comment-related imports

from akismet import Akismet
from django.conf import settings
from django.core.mail import mail_managers
from django.utils.encoding import smart_str
from django.contrib.sites.models import Site
from django.contrib.comments.models import Comment
from django.contrib.comments.signals import comment_will_be_posted
from django.contrib.comments.moderation import CommentModerator, moderator

# Fetch a Site  object so it would know where you were running the development
# server. Whenever you're  running with this database and settings file, you
# can get that Site object.

# current_site = Site.objects.get_current()
# akismet_api = Akismet(key=settings.AKISMET_API_KEY,
                       # blog_url="http://%s/" %Site.objects.get_current().domain)



Tag.get_absolute_url = models.permalink(
              lambda self: ('coltrane_all_items_by_tag', (), {'tag': self.name.lower()}))


 
        
        
# ------------------------------------------------------------------------------
# Content, Links etc
# ------------------------------------------------------------------------------

class Location(models.Model):
    
    
    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    slug = models.SlugField(unique=True, help_text=""" Suggested value automatically 
                            generated from title. Must be unique.""")
    description = models.TextField(blank=True)
    
    
    class Meta:
        ordering = ['title']
        verbose_name = _("Location")
        verbose_name_plural = _("Locations")
        
        
    def __unicode__(self):
        return self.title



class Category(models.Model):
    
    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    slug = models.SlugField(unique=True, 
                            help_text=""" Suggested value automatically 
                            generated from title. Must be unique.""")
    description = models.TextField()
    
    
    class Meta:
        ordering = ['title']
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        
        
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return ('coltrane_category_detail', (), {'slug': self.slug })
    
    def live_entry_set(self):
        from coltrane.models import Entry
        return self.entry_set.filter(status=Entry.LIVE_STATUS)
        

class LiveEntryManager(models.Manager):

    def get_query_set(self):
        return super(LiveEntryManager, self).get_query_set().filter(
                                                status=self.model.LIVE_STATUS)    

class Entry(models.Model):
    
    #----- Managers
    
    # custom manager enabling status based queries - becomes default, because 
    # the one daclared first will be  default
    
    live = LiveEntryManager() 
    objects = models.Manager() # standard manager(has to be reset manually)
        
    # Status constants
    
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    HIDDEN_STATUS = 3
    
    # Options for how to display a post
    
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DRAFT_STATUS, 'Draft'),
        (HIDDEN_STATUS, 'Hidden'),
    )
    
    # Core fields.
    article_icon = models.ImageField(upload_to=get_image_path, blank=True,  
                                     null=True)
    
    # Create a thumbnail for articles page
    article_icon_thumbnail_std = models.CharField(max_length=250,
                                                  blank=True, editable=False,
                                                  null=True)
    # Create a thumbnail for slider
    article_icon_thumbnail_slider = models.CharField(max_length=250,
                                                     blank=True, editable=False,
                                                     null=True)
    
    
    title = models.CharField(max_length=50,help_text='Maximum 50 characters.')
    excerpt = models.TextField(max_length=277,
                               blank=True, 
                               help_text= """A short summary of the entry. 
                               Maximum 277 characters. Optional.""")
    
    body = tinymce_models.HTMLField(blank=True, null=True,
                                    help_text="""You can use HTML markup - be
                                    careful!""")
    
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    
    # Date elements for easier navigation menu date archive lookup
    year = models.IntegerField(editable=False, blank=True, null=True)
    month = models.CharField(max_length=4, editable=False, blank=True, null=True)
    day = models.IntegerField(editable=False, blank=True, null=True)
    
    # Fields to store generated html.
    excerpt_html = models.TextField(editable=False, blank=True)
    body_html = models.TextField(editable=False, blank=True)
    
    # Metadata.
    author = models.ForeignKey(User)
    enable_comments = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS)
    slug = models.SlugField(unique=True, help_text=""" Suggested value 
                        automatically generated from title. Must be unique.""")
                        
    # categorize entries
    categories = models.ManyToManyField(Category)
    tags = TagField() # tagging module http://code.google.com/p/django-tagging/
    
    # featuring location
    
    locations = models.ManyToManyField(Location)
    
    
    class Meta:
        
        verbose_name = _("Entry")
        verbose_name_plural = _("Entries")
        ordering = ['-pub_date']
    
    
    def __unicode__(self):
        return self.title
        
        
    def save(self, force_insert=False, force_update=False):
        self.body_html = markdown(self.body)
        if self.excerpt:
            if len(self.excerpt) > 277: 
                self.excerpt = (self.excerpt[0:274] + u"...")
            self.excerpt_html = markdown(self.excerpt)
            
        # It's better to save this formatting once and save RAM by using more disc
        self.year = int(self.pub_date.strftime("%Y"))
        self.month = self.pub_date.strftime("%b").lower()
        self.day =  int(self.pub_date.strftime("%d"))
        
        ai = self.article_icon
        trans_title = space_to_underscore(transliterate(self.title[0:20]))
        
        url_path, url_name = split(ai.url)
        
        # Get rid of spaces quotes etc
        url_name = space_to_underscore(url_name)
        
        url_path = join(MEDIA_URL, IMG_UPLD_DIR, trans_title)
        self.article_icon_thumbnail_slider = join(url_path, 'slider_' + url_name)
        self.article_icon_thumbnail_std = join(url_path, 'standart_' + url_name)
        
        super(Entry, self).save(force_insert, force_update)
        
        # If there's an icon provided, let's create a thumbnail for
        # a slider and for ListView
        if ai:
            # Check that we're not doing duplicate work
            # Ommitting this nested if can lead to some nasty permission issues
            # in production.
            directory, filename = split(ai.path)
            file_list = listdir(directory)
             
            if not u''.join([u'standart_', filename]) in file_list:
                
                
                # For standart representation
                produce_resized_image(  ai, STANDARD_THUMBNAIL_SIZE, trans_title,
                                        u'standart_'
                                        )
                # For Slider
                produce_resized_image(  ai, SLIDER_THUMBNAIL_SIZE, trans_title,
                                        u'slider_'
                                    )
        
        
        
        
        
        
        
    @models.permalink
    def get_absolute_url(self):
        return ('coltrane_entry_detail', (),
               {'year': self.pub_date.strftime("%Y"),
                'month': self.pub_date.strftime("%b").lower(),
                'day' : self.pub_date.strftime("%d"),
                'slug': self.slug })
                
                
class Link(models.Model):
    
    # Metadata
    
    enable_comments = models.BooleanField(default=True)
    post_elsewhere = models.BooleanField('Post to Delicious', default=True)
    posted_by = models.ForeignKey(User)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    slug = models.SlugField(unique_for_date='pub_date',
                            help_text='Must be unique for the publication date.')
    title = models.CharField(max_length=250,
                             help_text='Maximum 250 characters')
    
    # The actual link content
    
    description = models.TextField(blank=True)
    description_html = models.TextField(editable=False, blank=True)
    url = models.URLField(unique=True)

templates/coltrane/base_categories.html
{% extends "coltrane/base.html" %}
{% block title %}| Categories{% endblock %}
{% block bodyclass %}categories{% endblock %}
{% block content %}{% endblock %}
{% block whatis %}{% endblock %}

templates/coltrane/base_entries.html
{% extends "coltrane/base.html" %}
{% block title %}| Entries{% endblock %}
{% block bodyclass %}entries{% endblock %}
{% block content %}{% endblock %}
{% block whatis %}{% endblock %}

templates/coltrane/category_detail.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}{{ block.super }} | {{ category.title }} {% endblock %}

{% block content %}
    <h2>"{{ category.title }}" Entries</h2>
    {% for object in object_list %}
      <p><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></p>
    {% endfor %}
{% endblock %}

{% block whatis %}
<p>
    This is a list of  {{ object_list.count }} entries contained
    in "{{ category.title }}" category.
</p>
{% endblock %}

templates/coltrane/date_archive.html
{% load coltrane_tags %}
<ul class="accordion_level2">
    <!-- This fetches {{model}} archive menu from the db -->
    <!-- A lame hardcoding, but it's faster than querying DB for a year every time -->
    {% get_years as years %}
    {% for year in years %}  
        <li>
            <a href="{% url 'coltrane_entry_archive_year' year %}"> 
                {{ year }}
            </a>
            {% i_get_active_dates of coltrane.{{model}} as nonempty_months that_have pub_date__year=year %}
            <ul class="accordion_level3">
                
                {% for month_pub in nonempty_months %}
                   <li>
                        <a href="{% url 'coltrane_entry_archive_month' year month_pub|date:"b" %}">
                            {{ month_pub|date:"F" }} {{ year }}
                        </a>
                       {% i_get_active_dates of coltrane.{{model}} as nonempty_days that_have pub_date__year=year pub_date__month=month_pub.month %}
                        <ul>
                            {% for day_pub in nonempty_days %}
                                <li >
                                    <a href="{% url 'coltrane_entry_archive_day' year month_pub|date:"b" day_pub.day %}">
                                        {{ day_pub.day }} {{ month_pub|date:"F" }} {{ year }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>    
                    </li>
                    
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

templates/coltrane/entries_by_tag.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}{{ block.super }} | {{ tag.name }} Entries{% endblock %}


{% block content %}
    <h2>Entries tagged with '{{ tag.name }}'</h2>
    {% for object in object_list %}
      <p><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></p>
    {% endfor %}
{% endblock %}

{% block whatis %}
<p>This is a list of the latest entries with the {{ tag.name }} tag.</p>
{% endblock %}

templates/coltrane/entry_archive.html
{% extends "coltrane/blog_base.html" %}

{% block title %}{{ block.super }} | Статьи. {% endblock %}

{% block content %}







<div id="templatemo_content_wrapper">
	<div id="templatemo_content">
        
        
		<div id="main_content">
            
            {% load endless %}
            {% paginate object_list %}  
            
            {% for entry in object_list %}
            <div class="post_section">
                
                <a href="{{ entry.get_absolute_url }}">
                <h2 class="entry_title">{{ entry.title }}</h2>
                </a>
                
                {{ entry.pub_date|date:"F j, Y" }} in 
                {% for category in entry.categories.all %}
                    <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                    {% if forloop.last %}{% else %}
                    {% ifequal forloop.revcounter0 1 %}and {% else %}, {% endifequal %}
                    {% endif %}
                {% endfor %}
                            
                by <a href="/" target="_parent">{{ entry.author }}</a>
                
                <div class="post_content">
                    
                    <div class="right">
                    <a href="{{ entry.get_absolute_url }}"><img src="{{ entry.article_icon_thumbnail_std}}" alt="{{ entry.title }}" /></a>                </div>
                    
                    <div class="left">
                        {% if entry.excerpt_html %}
                        {{ entry.excerpt_html|safe }}
                        {% else %}
                        {{ entry.body_html|truncatewords_html:"50"|safe }}
                        {% endif %}
                        <a href="{{ entry.get_absolute_url }}">Читать дальше...</a> | <a href="#">Комментарии (128)</a>
                    </div>
                    
                    <div class="cleaner"></div>
                </div>
                
                
                
            </div>
            
            {% endfor %}
            
            {% show_pages %}
            
        </div> <!-- end of main_content -->
        
        {% include "osov/sidebar.html" %}
        
        
		<div class="cleaner"></div>
    </div> <!-- end of content -->
    
</div> <!-- end of content_wrapper --> 


{% endblock %}




{% block whatis %}
<p>This is a list of the latest {{ latest.count }} entries published in
my blog.</p>
{% endblock %}

templates/coltrane/entry_archive_day.html
{% extends request.is_ajax|yesno:"base_content_ajax.html,base_entries.html" %}

{% block title %}
    {{ block.super }} | Entries in {{ month|date:"F, Y" }}
{% endblock %}

{% block content %}
    {% for entry in object_list %}
        <a href="{{ entry.get_absolute_url }}">
            <h2 class="entry_title">{{ entry.title }}</h2>
        </a>
        <p>Published on {{ entry.pub_date|date:"F j, Y" }}</p>
        {% if entry.excerpt_html %}
            {{ entry.excerpt_html|safe }}
        {% else %}
            {{ entry.body_html|truncatewords_html:"50"|safe }}
        {% endif %}
        <p><a href="{{ entry.get_absolute_url }}">Read full entry. . .</a></p>
    {% endfor %}
{% endblock %}
{% block whatis %}
    <p>This is a list of entries published in my
                                            blog in {{ day|date:"j F, Y" }}.</p>
{% endblock %}

templates/coltrane/entry_archive_month.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}
    {{ block.super }} | Entries in {{ month|date:"F, Y" }}
{% endblock %}

{% block content %}
    {% for entry in object_list %}
        <a href="{{ entry.get_absolute_url }}">
            <h2 class="entry_title">{{ entry.title }}</h2>
        </a>
        <p>Published on {{ entry.pub_date|date:"F j, Y" }}</p>
        {% if entry.excerpt_html %}
            {{ entry.excerpt_html|safe }}
        {% else %}
            {{ entry.body_html|truncatewords_html:"50"|safe }}
        {% endif %}
        <p><a href="{{ entry.get_absolute_url }}">Read full entry. . .</a></p>
    {% endfor %}
{% endblock %}
{% block whatis %}
    <p>This is a list of entries published in my
                                            blog in {{ month|date:"F, Y" }}.</p>
{% endblock %}

templates/coltrane/entry_archive_year.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}

{% block title %}{{ block.super }} | {{ year }}{% endblock %}

{% block content %}
    <ul>
    {% for month in date_list %}
        <li><a href="{% url 'coltrane_entry_archive_month' year month|date:"b" %}">
            {{ month|date:"F" }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

{% block whatis %}
<p>This is a list of months in {{ year }} in which entries were published in the blog.</p>
{% endblock %}

templates/coltrane/entry_index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Entries index</title>
    </head>
    <body>
        <h1>Entries indexsdfsdf</h1>
        {% for entry in entry_list %}
            <h2 >{{ entry.title }}</h2>
            <p>Published on {{ entry.pub_date|date:"F j, Y" }}</p>
            {% if entry.excerpt_html %}
                {{ entry.excerpt_html|safe }}
            {% else %}
                {{ entry.body_html|truncatewords_html:"50"|safe }}
            {% endif %}
            <p><a href="{{ entry.get_absolute_url }}">Read full entry</a></p>
        {% endfor %}
    </body>
</html>

templates/coltrane/link_archive.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}{{ block.super }} | Latest links{% endblock %}

{% block content %}
    {% for link in latest %}
      <h2>{{ link.title }}</h2>
      <p>Published on {{ link.pub_date|date:"F j, Y" }}</p>
      {% if link.description_html %}
       {{ link.description_html|truncatewords_html:"50"|safe }}
      {% endif %}
      <p><a href="{{ link.get_absolute_url }}">See more details</a></p>
    {% endfor %}
{% endblock %}

{% block whatis %}
<p>This is a list of the latest {{ latest.count }} links published in the blog.</p>
{% endblock %}

templates/coltrane/link_archive_day.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}{{ block.super }} | Links on {{ day|date:"F j, Y" }}{% endblock %}

{% block content %}
    {% for link in object_list %}
      <h2>{{ link.title }}</h2>
      <p>Published on {{ link.pub_date|date:"F j, Y" }}</p>
      {% if link.description_html %}
       {{ link.description_html|truncatewords_html:"50"|safe }}
      {% endif %}
      <p><a href="{{ link.get_absolute_url }}">See more details</a></p>
    {% endfor %}
{% endblock %}

{% block whatis %}
<p>This is a list of links published on {{ day|date:"F j, Y" }}.</p>
{% endblock %}

templates/coltrane/link_archive_month.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}{{ block.super }} | Links in {{ month|date:"F, Y" }}{% endblock %}

{% block content %}
    {% for link in object_list %}
      <h2>{{ link.title }}</h2>
      <p>Published on {{ link.pub_date|date:"F j, Y" }}</p>
      {% if link.description_html %}
       {{ link.description_html|truncatewords_html:"50"|safe }}
      {% endif %}
      <p><a href="{{ link.get_absolute_url }}">See more details</a></p>
     {% endfor %}
{% endblock %}

{% block whatis %}
<p>This is a list of links published in {{ month|date:"F, Y" }}.</p>
{% endblock %}

templates/coltrane/link_archive_year.html
{% extends request.is_ajax|yesno:"coltrane/base_content_ajax.html,coltrane/base_entries.html" %}
{% block title %}{{ block.super }} | {{ year }}{% endblock %}

{% block content %}
    <ul>
    {% for month in date_list %}
      <li><a href="{% url 'coltrane_link_archive_month year' ,month|date:"b" %}">{{ month|date:"F" }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

{% block whatis %}
<p>This is a list of months in {{ year }} in which links were published in the blog.</p>
{% endblock %}